rvm: 1.9.3
env:
- PUPPET_VERSION=3.6
- PUPPET_VERSION=3.4
notifications:
  hipchat:
    rooms:
      secure: OoKJMDdxaVJJBeLSyGN1Yf3ks189c5rZ2wj8OtlqkHtYlWDr8ViumJTMxWFNl5EUbx+BKCMArTsx9u4ahYvdJzaDLNaKD0l4hXQ6NdxrziI8y2boQdAeRXzPK02jRo3b3GG3Nmia7k5xkXF7Oztb5kT/q5hPM+Lbrq+CEGmi60U=
before_deploy: "puppet module build"
deploy:
  provider: releases
  api_key:
    secure: mNUgeZTU9Pff8ECKGg25rbriah62TkHUBF01o26PMvXnF1P59Eho5+K9+M4NJftiXVipDbDTgWq6/vr6k20IEXqBXtnj3Ez9PM89vEtW4lQRhIdc3aOO5MzTifk/zOAAaLftbwW6gkZ1/dw23zNMLTVkIMntnxk2/vTlex5noDU=
  file: pkg/xebialabs-xldeploy-1.0.2.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs/puppet-xldeploy
